/* Generated by tools/export_checkpoint.py. Do not edit manually. */
#ifndef FM_CSSD_LDA_PARAMS_H
#define FM_CSSD_LDA_PARAMS_H

#include <stdint.h>
#include "fm_cssd_lda.h"

extern const float fm_bp_sos[FM_CSSD_LDA_BP_SOS_SECTIONS][6u];
extern const float fm_erd_sos[FM_CSSD_LDA_ERD_SOS_SECTIONS][6u];
extern const float fm_bp_initial_state[FM_CSSD_LDA_BP_SOS_SECTIONS][2u];
extern const float fm_erd_initial_state[FM_CSSD_LDA_ERD_SOS_SECTIONS][2u];
extern const float fm_bp_spatial_filters[2u][FM_CSSD_LDA_CHANNELS];
extern const float fm_erd_spatial_filters[2u][FM_CSSD_LDA_CHANNELS];
extern const uint8_t fm_trend_indices[19u];
extern const float fm_bp_lda_weights[8u];
extern const float fm_bp_lda_bias;
extern const float fm_erd_lda_weights[8u];
extern const float fm_erd_lda_bias;
extern const float fm_trend_lda_weights[38u];
extern const float fm_trend_lda_bias;
extern const float fm_fusion_weights[3u];
extern const float fm_fusion_bias;

#endif
